-- MySQL Script generated by MySQL Workbench
-- Sun Oct 17 09:06:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bar_res_db` DEFAULT CHARACTER SET utf8 ;
USE `bar_res_db` ;

-- -----------------------------------------------------
-- Table `bar_res_db`.`anuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anuncio` (
  `idAnuncio` INT NOT NULL AUTO_INCREMENT,
  `nomUsuario` VARCHAR(50) NOT NULL,
  `categoria` ENUM('Restaurante', 'Restaurante-Bar', 'Bar', 'Puesto de Comida') NOT NULL,
  `titulo` VARCHAR(50) NOT NULL,
  `contenido` VARCHAR(400) NOT NULL,
  `imagen` VARCHAR(60) NULL,
  `fechPublic` TIMESTAMP(20) NOT NULL,
  `fechTermino` DATE NULL,
  PRIMARY KEY (`idAnuncio`),
  INDEX `FK_nomUsuario` () )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nomUsuario` VARCHAR(50) NOT NULL,
  `categoria` ENUM('Restaurante', 'Restaurante-Bar', 'Bar', 'Puesto de Comida') NOT NULL,
  `email` VARCHAR(15) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `nomUsuario` (`nomUsuario` ASC) ,
  CONSTRAINT `FK_idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`anuncio` (`idAnuncio`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
